#!/bin/bash

set -e

post_date="$( date -ju '+%Y-%m-%d %H:%M:%S UTC' )"
post_link="$1"

[[ $post_link =~ ^http ]] || { echo "link fail"; exit 1; }
post_quote="$(pbpaste)"
[[ -n $post_quote ]] || { echo "paste fail"; exit 1; }
echo "> \"$post_quote\""; sleep 3

post_id="$((1+$( ls -1r posts/ | head -n1 | cut -d/ -f2 | cut -d. -f1 )))"
[[ -n $post_id ]] || { echo "id fail"; exit 1; }

cat <<EOF > posts/$post_id.rst
.. date: $post_date
.. link: $post_link

   $post_quote
EOF

nikola build

cd output
git add -A
git commit -m $post_id
git push origin HEAD:master
cd ..
git add posts/$post_id.rst floatingatoll.github.io
git commit -m $post_id
git push origin HEAD:master
