#!/bin/bash

set -e

source ~/nikola/bin/activate

nikola build

cd output
git add -A
git commit -m rebuild
git push origin HEAD:master
cd ..
git commit -m rebuild -- floatingatoll.github.io
git push origin HEAD:master
